### ISSUE TITLE
Request for access to data

### ISSUE THREAD

**Issue by Miraclove** [hitercs/WikiInfo2Text#3]
I check the Google Drive file for the dataset but it is unavaliable to download right now. Could you update the link for the dataset? That would be really helpful!

**Comment by hitercs** [comment]
Hi @Miraclove,

Thanks! I've changed the download link to the Baidu disk, please have a try:

URL: https://pan.baidu.com/s/16bSdvB8eDNWFDKwXyWwlWA  

Password: xzik

**Comment by Miraclove** [comment]
Thanks! This dataset is impressive. Have already downloaded.
